{% set name = "tardigrade_abaqus_tools" %}
{% set version = "0.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: '..'

build:
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script:
    - set -x
    # Build and install c++ libraries
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib
    - cmake --install build --prefix ${PREFIX}
  skip: true  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.30
    - make
  host:
    - breathe >=4.3.0
    - doxygen
    - eigen >=3.3.7
    - libboost-python-devel >=1.82
    - setuptools >=77
    - setuptools_scm >=8
    - sphinx >=3.0.4
    - sphinx_rtd_theme >=0.4.3
    - sphinxcontrib-bibtex
    - tardigrade_vector_tools >=0.8.7
  run:
    - eigen >=3.3.7

test:
  requires:
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.30
    - libboost-python-devel >=1.82
    - doxygen
    - sphinx >=3.0.4
    - tardigrade_vector_tools >=0.8.7
  source_files:
    - CMakeLists.txt
    - src/cpp/tests/CMakeLists.txt
    - src/cpp/tests/test_tardigrade_abaqus_tools.cpp
  commands:
    - set -x
    - cmake -S . -B build -DCMAKE_BUILD_TYPE=conda-test -DCMAKE_INSTALL_LIBDIR=lib
    - cmake --build build --target test_tardigrade_abaqus_tools
    - ctest --test-dir build --output-on-failure -R test_tardigrade_abaqus_tools

about:
  home: https://github.com/UCBoulder/tardigrade_abaqus_tools
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'A collection of tools for C++ that make interfacing with Abaqus subroutines easier and less prone to error.'
  description: |
    tardigrade-abaqus-tools A collection of tools for C++ that make interfacing with Abaqus
    subroutines easier and less prone to error.
  dev_url: https://github.com/UCBoulder/tardigrade_abaqus_tools
